      SUBROUTINE ALOOP(NA,LA,ETAA,ANORM,EVECA,EVALA,OCCA,FOCKA,GAMMAA,
     X                 STOVLA,STKINA,STPOTA,LVA,MVA,VEXPA,ZPOT2A,CPOT2A,
     X                 PKPOTA,PROJEC,VFIT2A,VCOEFA,SCRAT,CORE,
     X                 COORD,EWMAT,OVLP,CHARGE,POPUL,
     X                 YLMNRM,OMEGAI,OMEGAJ,
     X                 A,B,D,INDEX,KREC,CGC,QREALY,EVALX,OCCX,EVECX)
      IMPLICIT REAL*8(A-H,O,P,R-Z),LOGICAL*1(Q)
	CHARACTER*2 LATOMA
C-----------------------------------------------------------------------
C
C     ALOOP...
C
C-----------------------------------------------------------------------
      COMMON /PARMS/ APARM(20),IPARM(50),QPARM(50)
      DIMENSION QFLAGA(8)
      EQUIVALENCE (QPARM(1),QRSTRT),  (QPARM(4),QOPEN),
     X            (QPARM(5),QFIRST),
     X            (QPARM(6),QLAST),   (QPARM(7),QDEBUG),
     X            (QPARM(8),QSEPAT),  (QPARM(9),QCMPTD),
     X            (QPARM(11),QFLAGA(1)),(QPARM(12),QVIRTA),
     X            (QPARM(15),QFLIPA)
      EQUIVALENCE (IPARM(1),NATOM),   (IPARM(2),NELEM),
     X            (IPARM(3),NUCZA),   (IPARM(4),IEQATA),
     X            (IPARM(5),MSTOA),
     X            (IPARM(6),NORBA),   (IPARM(7),IORBTA),
     X            (IPARM(8),NORBT),   (IPARM(9),N2ORBT),
     X            (IPARM(10),IATOM),  (IPARM(11),JDFATA),
     X            (IPARM(13),N2ATOM), (IPARM(16),MDFATA),
     X            (IPARM(19),NNMXM1), (IPARM(21),LMXP1),
     X            (IPARM(22),LLMXP1), (IPARM(24),NCGC),
     X            (IPARM(26),IELEMA),
     X            (IPARM(27),M2STOA), (IPARM(28),L3MX),
     X            (IPARM(30),NABDIM), (IPARM(31),NVTRMA),
     X            (IPARM(32),NSTOA),  (IPARM(33),ISPIN),
     X            (IPARM(34),NYLM),   (IPARM(35),N2ORBA),
     X            (IPARM(39),IUNITA),
     X            (IPARM(41),JSTOTA),  (IPARM(42),MSTOT)
      COMMON /BPARMS/ IELEMB,IUNITB,MDFATB,JDFAT1,MEQATB,JATOM,
     X                NSTOB,MSTOB,NORBB,N2ORBB,IORBTB,M2STOB,JSTOTB,
     X                NVTRMB
      DIMENSION NA(NSTOA),                LA(NSTOA),
     X          ETAA(NSTOA),              ANORM(NSTOA),
     X          EVECA(MSTOA,NORBA,ISPIN), EVALA(NORBA,ISPIN),
     X          STOVLA(M2STOA),           STKINA(M2STOA),
     X          STPOTA(M2STOA,NVTRMA),    VEXPA(NVTRMA),
     X          LVA(NVTRMA),              MVA(NVTRMA),
     X          OCCA(NORBA,ISPIN),        ZPOT2A(M2STOA),
     X          VFIT2A(NVTRMA),           FOCKA(N2ORBA,ISPIN),
     X          GAMMAA(NORBA,ISPIN),      PROJEC(MSTOA,MSTOA,ISPIN),
     X          CPOT2A(M2STOA),           PKPOTA(M2STOA,6,ISPIN),
     X          VCOEFA(NVTRMA),           COORD(3,NATOM),
     X          OVLP(N2ORBT,ISPIN),       EWMAT(N2ORBT,ISPIN),
     X          CHARGE(3,NATOM),          POPUL(NORBT,ISPIN),
     X          OMEGAI(NNMXM1,NNMXM1),    OMEGAJ(NNMXM1,NNMXM1),
     X          A(NABDIM),                B(NABDIM),
     X          D(L3MX,2),                INDEX(1),
     X          SCRAT(MSTOA,MSTOA,2),     KREC(N2ATOM),
     X          CGC(NCGC),                YLMNRM(NYLM),
     X          EVALX(NORBT,ISPIN),       OCCX(NORBT,ISPIN),
     X          EVECX(MSTOT,NORBT,ISPIN)       
      COMMON /IODATA/ IUNIT(20),LENBUF
      EQUIVALENCE (IUNIT(3),IUNIT3), (IUNIT(4),IUNIT4),
     X            (IUNIT(6),IW),     (IUNIT(7),IP),
     X            (IUNIT(8),IUDUMP), (IUNIT(10),IUCSF)
	CHARACTER*8 ROUTIN
      COMMON /DYNAMC/ LISTAR(500),IPTR(10),NNIA(10),NID(10),NXARG(10),
     X                ROUTIN(10),NROUT
      COMMON /FIXED/  MXCORE,NWCORE,NWORDS
	CHARACTER*8 SPIN
      COMMON /CHARGS/ ZNSUM,ELSUM,ELDIF,ELECS(2),SPIN(2),ORBOCC,CHTRAN
      COMMON /MODPOT/ WGT0,WGT1,WGT2,WGTC,WGTV,VDAMP,VACCEL,
     X                TFEXP(4),TFCOEF(4),LTF(4),MXTF
      COMMON /PUNCHK/ RENRMA,RENRMB,KATOM,KORB,KSP,QPNCHK
C-----------------------------------------------------------------------
C  FIXED CORE ALLOCATION:
C
      DIMENSION CORE(1),IC(30)
C-----------------------------------------------------------------------
      DATA HALF/0.50D0/,ONE/1.0D0/
	  
      READ (IUNITA) LATOMA,NUCZA,NA,LA,ETAA,ANORM
      READ (IUNITA) STOVLA,STKINA,STPOTA,LVA,MVA,VEXPA
      REWIND IUNITA

      DO 240 JDFATA=1,MDFATA  
      READ (IUNIT3) QFLAGA,NEQATA,XA,YA,ZA,EVECA,EVALA,OCCA,FOCKA,
     X     GAMMAA,CPOT2A,VFIT2A,VCOEFA,PKPOTA,ZPOT2A,TOTENA,ZZREPA,RMAXA
      IF (QVIRTA) GO TO 40
	  
      DO 30 ISP=1,ISPIN
      CALL CTSC(EVECA(1,1,ISP),STOVLA,SCRAT,SCRAT(1,1,2),MSTOA,NORBA)
      CALL INSRTD(SCRAT(1,1,2),OVLP(1,ISP),IORBTA+1,NORBA)
      CALL INSRTD(FOCKA(1,ISP),EWMAT(1,ISP),IORBTA+1,NORBA)
      KORBTA=IORBTA
	DO 20 IORBA=1,NORBA
         KORBTA=KORBTA+1
         EVALX(KORBTA,ISP)=EVALA(IORBA,ISP)
         OCCX(KORBTA,ISP)=OCCA(IORBA,ISP)
         KSTOTA=JSTOTA
	   DO 10 JSTOA=1,MSTOA
            KSTOTA=KSTOTA+1
            EVECX(KSTOTA,KORBTA,ISP)=EVECA(JSTOA,IORBA,ISP)
   10    CONTINUE
   20 CONTINUE
   30 CONTINUE

   
      ZNSUM=ZNSUM+CHARGE(1,IATOM+1)
      ELSUM=ELSUM+CHARGE(2,IATOM+1)
      ELDIF=ELDIF+CHARGE(3,IATOM+1)
	  
   40 CONTINUE
      IATOM=IATOM+1
      QPNCHK=.FALSE.
      IF (QLAST.AND.(KATOM.NE.0).AND.(IATOM.EQ.1))
     X   WRITE(IP,1200) NORBT,'Phatpsy.car'
      IF (QLAST.AND.(IATOM.EQ.IABS(KATOM))) QPNCHK = .TRUE. 
      IF (QLAST.AND.(IABS(KATOM).GT.NATOM).AND..NOT.QVIRTA) 
     X   QPNCHK = .TRUE. 
      IF ((KATOM.LT.0).AND.(IABS(KORB).GT.NORBA)) QPNCHK = .FALSE.
      IF (.NOT.QPNCHK) GO TO 70 

      RENRMA=ONE
      RENRMB=ONE

      IF (KORB.EQ.0) GOTO 65

      JSTOA=0
	  
      DO 60 ISTOA=1,NSTOA
      LLAP1=2*LA(ISTOA)+1
      DO 50 IMLA=1,LLAP1
      MLA=IMLA-LA(ISTOA)-1
      JSTOA=JSTOA+1

      IF (IABS(KORB).LE.NORBA) THEN
         IF ((KSP.GT.0).AND.(KSP.LE.ISPIN)) THEN
           WRITE (IP,1000) NA(ISTOA),LA(ISTOA),MLA,ETAA(ISTOA),
     X                     ANORM(ISTOA),LATOMA,JDFATA,XA,YA,ZA,
     X                     1,1
           WRITE (IP,1100) OCCA(KORB,KSP)
           WRITE (IP,1100) EVALA(KORB,KSP)
           WRITE (IP,1100) EVECA(JSTOA,IABS(KORB),KSP)
         ENDIF
         IF ((KSP.EQ.0).OR. (KSP.GT.ISPIN)) THEN
           WRITE (IP,1000) NA(ISTOA),LA(ISTOA),MLA,ETAA(ISTOA),
     X                     ANORM(ISTOA),LATOMA,JDFATA,XA,YA,ZA,
     X                     1,2
           WRITE (IP,1100) OCCA(IABS(KORB),1),
     X                     OCCA(IABS(KORB),ISPIN)
           WRITE (IP,1100) EVALA(IABS(KORB),1),
     X                     EVALA(IABS(KORB),ISPIN)
           WRITE (IP,1100) EVECA(JSTOA,IABS(KORB),1),
     X                     EVECA(JSTOA,IABS(KORB),ISPIN)
	 ENDIF
      ELSE
         WRITE (IP,1000) NA(ISTOA),LA(ISTOA),MLA,ETAA(ISTOA),
     X                   ANORM(ISTOA),LATOMA,JDFATA,XA,YA,ZA,
     X                   NORBA,ISPIN
         WRITE (IP,1100) ((OCCA(I,J),I=1,NORBA),J=1,ISPIN)
         WRITE (IP,1100) ((EVALA(I,J),I=1,NORBA),J=1,ISPIN)
         WRITE (IP,1100) ((EVECA(JSTOA,I,J),I=1,NORBA),J=1,ISPIN)
      ENDIF   

   50 CONTINUE
   60 CONTINUE
      GOTO 70
   
   65 CONTINUE
      DO 67 NV=1,NVTRMA
      NVA=0
      VNORM=1.0
      WRITE (IP,1000) NVA,LVA(NV),MVA(NV),VEXPA(NV),VNORM,
     X     LATOMA,JDFATA,XA,YA,ZA,1,1
      WRITE (IP,1100) ONE
      WRITE (IP,1100) ONE
      WRITE (IP,1100) VCOEFA(NV)
   67 CONTINUE

   70 CONTINUE
      CALL SCMULT(CPOT2A,VDAMP,M2STOA)
      CALL SCMULT(ZPOT2A,VDAMP,M2STOA)
      CALL SCMULT(VFIT2A,VDAMP,NVTRMA)
      CALL SCMULT(PKPOTA,VDAMP,3*M2STOA)
      IF (QOPEN) CALL SCMULT(PKPOTA(1,1,2),VDAMP,3*M2STOA)
C      CALL SCMULT(PKPOTA,HALF,3*M2STOA)
C      IF (QOPEN) CALL SCMULT(PKPOTA(1,1,2),HALF,3*M2STOA)
      ZZREPA=VDAMP*ZZREPA
	  
   90 CONTINUE
      IF (QVIRTA) GO TO 110
      IORBTB=IORBTA+NORBA
      JATOM=IATOM
      JDFAT1=JDFATA
      IF (NEQATA.EQ.0) JDFAT1=MOD(JDFATA,MDFATA)+1
      MEQATB=NEQATA
      INCR=1
      IF ((JDFATA.EQ.MDFATA).AND.(NEQATA.EQ.0)) INCR=0
      QSKIP=(INCR.EQ.1)
      NELEMB=NELEM+INCR
      MDFATB=MDFATA
      NORBB=NORBA
	  
      DO 100 IELEMB=1,NELEMB
      IUNITB=IUNIT(11+MOD(IELEMA+IELEMB-1-INCR,NELEM))
      READ (IUNITB) NSTOB,MSTOB,NORBB,NVTRMB
      M2STOB=INDEX(MSTOB)+MSTOB
      IF (JATOM.EQ.NATOM) REWIND IUNIT3
      IF (.NOT.QSKIP) READ (IUNIT3) MDFATB
      N2ORBB=INDEX(NORBB)+NORBB
      MSTOX=MAX0(MSTOA,MSTOB)
      M2STOX=INDEX(MSTOX)+MSTOX
C-----------------------------------------------------------------------
C  FIXED CORE ALLOCATION OFFSETS:
C
      IC(1)=1
      IC(2)=IC(1)+(NSTOB+1)/2
      IC(3)=IC(2)+(NSTOB+1)/2
      IC(4)=IC(3)+NSTOB
      IC(5)=IC(4)+NSTOB
      IC(6)=IC(5)+M2STOB
      IC(7)=IC(6)+M2STOB
      IC(8)=IC(7)+NVTRMB
      IC(9)=IC(8)+M2STOB*6*ISPIN
      IC(10)=IC(9)+MSTOB*NORBB*ISPIN
      IC(11)=IC(10)+NORBB*ISPIN
      IC(12)=IC(11)+NORBB*ISPIN
      IC(13)=IC(12)+N2ORBB*ISPIN
      IC(14)=IC(13)+NORBB*ISPIN
      IC(15)=IC(14)+M2STOB
      IC(16)=IC(15)+M2STOB
      IC(17)=IC(16)+M2STOB*NVTRMB
      IC(18)=IC(17)+NVTRMB
      IC(19)=IC(18)+NVTRMB
      IC(20)=IC(19)+NVTRMB
      IC(21)=IC(20)+NVTRMB
      IC(22)=IC(21)+M2STOA*NVTRMB
      IC(23)=IC(22)+LLMXP1*NSTOA*NSTOB
      IC(24)=IC(23)+MSTOA*MSTOB
      IC(25)=IC(24)+MSTOA*NORBB*ISPIN
      IC(26)=IC(25)+NORBA*NORBB*ISPIN
      IC(27)=IC(26)+M2STOX
      IC(28)=IC(27)+M2STOB
      IC(29)=IC(28)+MSTOX*MSTOB
      NWORDS=IC(29)+LMXP1
      NWCORE=NWCORE-NWORDS
      IF (NWCORE.LE.0) CALL BOMB(0)

      CALL BLOOP(CORE(IC(1)),CORE(IC(2)),CORE(IC(3)),CORE(IC(4)),
     X           CORE(IC(5)),CORE(IC(6)),CORE(IC(7)),CORE(IC(8)),
     X           CORE(IC(9)),CORE(IC(10)),CORE(IC(11)),CORE(IC(12)),
     X           CORE(IC(13)),CORE(IC(14)),CORE(IC(15)),CORE(IC(16)),
     X           CORE(IC(17)),CORE(IC(18)),CORE(IC(19)),CORE(IC(20)),
     X           CORE(IC(21)),CORE(IC(22)),CORE(IC(23)),CORE(IC(24)),
     X           CORE(IC(25)),CORE(IC(26)),CORE(IC(27)),CORE(IC(28)),
     X           CORE(IC(29)),                          NA,LA,ETAA,
     X           ANORM,ZPOT2A,CPOT2A,STOVLA,STPOTA,LVA,MVA,VEXPA,VCOEFA,
     X           GAMMAA,
     X           VFIT2A,PKPOTA,PROJEC,EVALA,OCCA,EVECA,POPUL,
     X           OVLP,COORD,YLMNRM,
     X           OMEGAI,OMEGAJ,A,B,D,INDEX,KREC,ZZREPA,RMAXA,CGC,QREALY,
     X           EVALX,OCCX,EVECX)

      NWCORE=NWCORE+NWORDS
      JDFAT1=1
      QSKIP=.FALSE.
  100 CONTINUE
  
      IF (QPNCHK.AND.KATOM.LT.0.AND.KORB.NE.0) 
     X   WRITE (IP,2000) RENRMA,RENRMB
      IF (QPNCHK.AND.(KSP.GT.0).AND.(KSP.LE.ISPIN)) 
     X   WRITE (IW,3000) KORB,SPIN(KSP),LATOMA,JDFATA,IP
      IORBTA=IORBTA+NORBA
	JSTOTA=JSTOTA+MSTOA
	  
  110 CONTINUE
      WRITE (IUNIT4) QFLAGA,NEQATA,XA,YA,ZA,EVECA,EVALA,OCCA,FOCKA,
     X     GAMMAA,CPOT2A,VFIT2A,VCOEFA,PKPOTA,ZPOT2A,TOTENA,ZZREPA,RMAXA
      IF (NEQATA.EQ.0) GO TO 240
	  
      DO 230 IEQATA=1,NEQATA
      READ (IUNIT3) QFLAGA,ISYMA,IXYZA,XA,YA,ZA,EVECA,EVALA,OCCA,FOCKA,
     X     GAMMAA,CPOT2A,VFIT2A,VCOEFA,PKPOTA,ZPOT2A,TOTENA,ZZREPA,RMAXA
      IF (QVIRTA) GO TO 150
	  
      DO 140 ISP=1,ISPIN
      CALL CTSC(EVECA(1,1,ISP),STOVLA,SCRAT,SCRAT(1,1,2),MSTOA,NORBA)
      CALL INSRTD(SCRAT(1,1,2),OVLP(1,ISP),IORBTA+1,NORBA)
      CALL INSRTD(FOCKA(1,ISP),EWMAT(1,ISP),IORBTA+1,NORBA)
      KORBTA=IORBTA
	DO 130 IORBA=1,NORBA
         KORBTA=KORBTA+1
         EVALX(KORBTA,ISP)=EVALA(IORBA,ISP)
         OCCX(KORBTA,ISP)=OCCA(IORBA,ISP)
         KSTOTA=JSTOTA
	   DO 120 JSTOA=1,MSTOA
            KSTOTA=KSTOTA+1
            EVECX(KSTOTA,KORBTA,ISP)=EVECA(JSTOA,IORBA,ISP)
  120    CONTINUE
  130 CONTINUE
  140 CONTINUE
  
      ZNSUM=ZNSUM+CHARGE(1,IATOM+1)
      ELSUM=ELSUM+CHARGE(2,IATOM+1)
      ELDIF=ELDIF+CHARGE(3,IATOM+1)
	  
  150 CONTINUE
      IATOM=IATOM+1
      MATOMA=IEQATA*MDFATA+JDFATA
      QPNCHK=.FALSE.
      IF (QLAST.AND.(IATOM.EQ.IABS(KATOM))) QPNCHK = .TRUE. 
      IF (QLAST.AND.(IABS(KATOM).GT.NATOM).AND..NOT.QVIRTA) 
     X   QPNCHK = .TRUE. 
      IF ((KATOM.LT.0).AND.(IABS(KORB).GT.NORBA)) QPNCHK = .FALSE.
      IF (.NOT.QPNCHK) GO TO 180

      RENRMA=ONE
      RENRMB=ONE

      IF (KORB.EQ.0) GOTO 175

      JSTOA=0
	  
      DO 170 ISTOA=1,NSTOA
      LLAP1=2*LA(ISTOA)+1
      DO 160 IMLA=1,LLAP1
      MLA=IMLA-LA(ISTOA)-1
      JSTOA=JSTOA+1

      IF (IABS(KORB).LE.NORBA) THEN
         IF ((KSP.GT.0).AND.(KSP.LE.ISPIN)) THEN
           WRITE (IP,1000) NA(ISTOA),LA(ISTOA),MLA,ETAA(ISTOA),
     X                     ANORM(ISTOA),LATOMA,MATOMA,XA,YA,ZA,
     X                     1,1
           WRITE (IP,1100) OCCA(IABS(KORB),KSP)
           WRITE (IP,1100) EVALA(IABS(KORB),KSP)
           WRITE (IP,1100) EVECA(JSTOA,IABS(KORB),KSP)
         ENDIF
         IF ((KSP.EQ.0).OR. (KSP.GT.ISPIN)) THEN
           WRITE (IP,1000) NA(ISTOA),LA(ISTOA),MLA,ETAA(ISTOA),
     X                     ANORM(ISTOA),LATOMA,MATOMA,XA,YA,ZA,
     X                     1,2
           WRITE (IP,1100) OCCA(IABS(KORB),1),
     X                     OCCA(IABS(KORB),ISPIN)
           WRITE (IP,1100) EVALA(IABS(KORB),1),
     X                     EVALA(IABS(KORB),ISPIN)
           WRITE (IP,1100) EVECA(JSTOA,IABS(KORB),1),
     X                     EVECA(JSTOA,IABS(KORB),ISPIN)
	 ENDIF
      ELSE
         WRITE (IP,1000) NA(ISTOA),LA(ISTOA),MLA,ETAA(ISTOA),
     X                   ANORM(ISTOA),LATOMA,MATOMA,XA,YA,ZA,
     X                   NORBA,ISPIN
         WRITE (IP,1100) ((OCCA(I,J),I=1,NORBA),J=1,ISPIN)
         WRITE (IP,1100) ((EVALA(I,J),I=1,NORBA),J=1,ISPIN)
         WRITE (IP,1100) ((EVECA(JSTOA,I,J),I=1,NORBA),J=1,ISPIN)
      ENDIF   

  160 CONTINUE
  170 CONTINUE
      GOTO 180
   
  175 CONTINUE
      DO 177 NV=1,NVTRMA
      NVA=0
      VNORM=1.0
      WRITE (IP,1000) NVA,LVA(NV),MVA(NV),VEXPA(NV),VNORM,
     X     LATOMA,MATOMA,XA,YA,ZA,1,1
      WRITE (IP,1100) ONE
      WRITE (IP,1100) ONE
      WRITE (IP,1100) VCOEFA(NV)
  177 CONTINUE

  180 CONTINUE
      CALL SCMULT(CPOT2A,VDAMP,M2STOA)
      CALL SCMULT(ZPOT2A,VDAMP,M2STOA)
      CALL SCMULT(VFIT2A,VDAMP,NVTRMA)
      CALL SCMULT(PKPOTA,VDAMP,3*M2STOA)
      IF (QOPEN) CALL SCMULT(PKPOTA(1,1,2),VDAMP,3*M2STOA)
      ZZREPA=VDAMP*ZZREPA
      IF (QVIRTA) GO TO 220
      IORBTB=IORBTA+NORBA
      JATOM=IATOM
      JDFAT1=JDFATA
      IF (IEQATA.EQ.NEQATA) JDFAT1=MOD(JDFATA,MDFATA)+1
      MEQATB=NEQATA-IEQATA
      INCR=1
      IF ((IEQATA.EQ.NEQATA).AND.(JDFATA.EQ.MDFATA)) INCR=0
      QSKIP=(INCR.EQ.1)
      NELEMB=NELEM+INCR
      MDFATB=MDFATA
      NORBB=NORBA
	  
      DO 210 IELEMB=1,NELEMB
      IUNITB=IUNIT(11+MOD(IELEMA+IELEMB-1-INCR,NELEM))
      READ (IUNITB) NSTOB,MSTOB,NORBB,NVTRMB
      M2STOB=INDEX(MSTOB)+MSTOB
      IF (JATOM.EQ.NATOM) REWIND IUNIT3
      IF (.NOT.QSKIP) READ (IUNIT3) MDFATB
      N2ORBB=INDEX(NORBB)+NORBB
      MSTOX=MAX0(MSTOA,MSTOB)
      M2STOX=INDEX(MSTOX)+MSTOX
C-----------------------------------------------------------------------
C  FIXED CORE ALLOCATION OFFSETS:
C
      IC(1)=1
      IC(2)=IC(1)+(NSTOB+1)/2
      IC(3)=IC(2)+(NSTOB+1)/2
      IC(4)=IC(3)+NSTOB
      IC(5)=IC(4)+NSTOB
      IC(6)=IC(5)+M2STOB
      IC(7)=IC(6)+M2STOB
      IC(8)=IC(7)+NVTRMB
      IC(9)=IC(8)+M2STOB*6*ISPIN
      IC(10)=IC(9)+MSTOB*NORBB*ISPIN
      IC(11)=IC(10)+NORBB*ISPIN
      IC(12)=IC(11)+NORBB*ISPIN
      IC(13)=IC(12)+N2ORBB*ISPIN
      IC(14)=IC(13)+NORBB*ISPIN
      IC(15)=IC(14)+M2STOB
      IC(16)=IC(15)+M2STOB
      IC(17)=IC(16)+M2STOB*NVTRMB
      IC(18)=IC(17)+NVTRMB
      IC(19)=IC(18)+NVTRMB
      IC(20)=IC(19)+NVTRMB
      IC(21)=IC(20)+NVTRMB
      IC(22)=IC(21)+M2STOA*NVTRMB
      IC(23)=IC(22)+LLMXP1*NSTOA*NSTOB
      IC(24)=IC(23)+MSTOA*MSTOB
      IC(25)=IC(24)+MSTOA*NORBB*ISPIN
      IC(26)=IC(25)+NORBA*NORBB*ISPIN
      IC(27)=IC(26)+M2STOX
      IC(28)=IC(27)+M2STOB
      IC(29)=IC(28)+MSTOX*MSTOB
      NWORDS=IC(29)+LMXP1
      NWCORE=NWCORE-NWORDS
      IF (NWCORE.LE.0) CALL BOMB(0)

      CALL BLOOP(CORE(IC(1)),CORE(IC(2)),CORE(IC(3)),CORE(IC(4)),
     X           CORE(IC(5)),CORE(IC(6)),CORE(IC(7)),CORE(IC(8)),
     X           CORE(IC(9)),CORE(IC(10)),CORE(IC(11)),CORE(IC(12)),
     X           CORE(IC(13)),CORE(IC(14)),CORE(IC(15)),CORE(IC(16)),
     X           CORE(IC(17)),CORE(IC(18)),CORE(IC(19)),CORE(IC(20)),
     X           CORE(IC(21)),CORE(IC(22)),CORE(IC(23)),CORE(IC(24)),
     X           CORE(IC(25)),CORE(IC(26)),CORE(IC(27)),CORE(IC(28)),
     X           CORE(IC(29)),                          NA,LA,ETAA,
     X           ANORM,ZPOT2A,CPOT2A,STOVLA,STPOTA,LVA,MVA,VEXPA,VCOEFA,
     X           GAMMAA,
     X           VFIT2A,PKPOTA,PROJEC,EVALA,OCCA,EVECA,POPUL,
     X           OVLP,COORD,YLMNRM,
     X           OMEGAI,OMEGAJ,A,B,D,INDEX,KREC,ZZREPA,RMAXA,CGC,QREALY,
     X           EVALX,OCCX,EVECX)

      NWCORE=NWCORE+NWORDS
      JDFAT1=1
      QSKIP=.FALSE.	  
  210 CONTINUE
  
      IF (QPNCHK.AND.KATOM.LT.0.AND.KORB.NE.0) 
     X   WRITE (IP,2000) RENRMA,RENRMB
      IF (QPNCHK.AND.(KSP.GT.0).AND.(KSP.LE.ISPIN)) 
     X   WRITE (IW,3000) KORB,SPIN(KSP),LATOMA,MATOMA,IP
      IORBTA=IORBTA+NORBA
	JSTOTA=JSTOTA+MSTOA
	  
  220 CONTINUE
      WRITE (IUNIT4) QFLAGA,ISYMA,IXYZA,XA,YA,ZA,EVECA,EVALA,OCCA,
     X     FOCKA,GAMMAA,CPOT2A,VFIT2A,VCOEFA,PKPOTA,ZPOT2A,TOTENA,
     X     ZZREPA,RMAXA
  230 CONTINUE
  240 CONTINUE
  
      RETURN
	  
 1000 FORMAT(/,3I3,2F12.5,1X,A2,I3,3F10.5,I3,I2)
 1100 FORMAT(F10.5,$)
 1200 FORMAT(I4,A20,$)
 2000 FORMAT(/64X,F10.5)
 3000 FORMAT(//' ... THE',I3,1X,A8,' ORBITAL ON ATOM ',A2,I2,
     X       ' HAS BEEN PUNCHED ON UNIT',I3,' ...')
      END
