      SUBROUTINE DAMPV(EPOT2,PKPOT,ZPOT2,VPOT2,MSTO,M2STO,NVTERM,ISPIN,
     X                 VDAMP)
      IMPLICIT REAL*8(A-H,O-Z)
C-----------------------------------------------------------------------
C
C     DAMPV...
C
C        THIS ROUTINE DAMPS THE EXTERNAL POTENTIAL MATRIX ELEMENTS.
C     THIS INITIALIZES THE MATRICES TO A FRACTION OF THE OLD TO
C     WHICH A FRACTION OF THE NEW SHALL BE ADDED.
C
C     VARIABLE DEFINITIONS:
C
C        EPOT2(*,*)..... MODEL POTENTIAL MATRIX.
C        PKPOT(*,*,*)... PSEUDOPOTENTIAL (AND EXCHANGE) MATRIX.
C        ZPOT2(*)....... NUCLEAR ATTRACTION MATRIX.
C        VPOT2(*)....... INTERNAL MODEL POTENTIAL EVALUATED ON EXTERNAL
C                        SITES.
C        MSTO........... BASIS DIMENSION.
C        M2STO.......... =MSTO*(MSTO+1)/2.
C        NVTERM......... NUMBER OF TERMS IN INTERNAL MODEL POTENTIAL.
C        ISPIN.......... =1 --> SPIN-RESTRICTED, =2 --> UNRESCTRICTED.
C        VDAMP.......... DAMPING FACTOR (FRACTION OF OLD).
C
C-----------------------------------------------------------------------
      DIMENSION EPOT2(M2STO,ISPIN),PKPOT(M2STO,4,ISPIN),ZPOT2(M2STO),
     X          VPOT2(NVTERM)
      DO 40 ISP=1,ISPIN
      IJ=0
      DO 30 I=1,MSTO
      DO 20 J=1,I
      IJ=IJ+1
      EPOT2(IJ,ISP)=VDAMP*EPOT2(IJ,ISP)
      DO 10 K=1,2
      PKPOT(IJ,K,ISP)=VDAMP*PKPOT(IJ,K,ISP)
   10 CONTINUE
      IF (ISP.GT.1) GO TO 20
      ZPOT2(IJ)=VDAMP*ZPOT2(IJ)
   20 CONTINUE
   30 CONTINUE
   40 CONTINUE
      DO 50 NV=1,NVTERM
      VPOT2(NV)=VDAMP*VPOT2(NV)
   50 CONTINUE
      RETURN
      END
