      SUBROUTINE OUTPAK (MATRIX,NROW,NCTL)
C...........VERSION = 09/05/73/03
C.......................................................................
C
C OUTPAK PRINTS A REAL*8 SYMMETRIC MATRIX STORED IN ROW-PACKED LOWER
C
C TRIANGULAR FORM (SEE DIAGRAM BELOW) IN FORMATTED FORM WITH NUMBERED
C
C ROWS AND COLUMNS.  THE INPUT IS AS FOLLOWS:
C
C        MATRIX(*)...........PACKED MATRIX
C
C        NROW................NUMBER OF ROWS TO BE OUTPUT
C
C        NCTL................CARRIAGE CONTROL FLAG: 1 FOR SINGLE SPACE,
C                                                   2 FOR DOUBLE SPACE,
C                                                   3 FOR TRIPLE SPACE.
C
C THE MATRIX ELEMENTS ARE ARRANGED IN STORAGE AS FOLLOWS:
C
C        1
C        2    3
C        4    5    6
C        7    8    9   10
C       11   12   13   14   15
C       16   17   18   19   20   21
C       22   23   24   25   26   27   28
C
C AND SO ON.
C
C OUTPAK IS SET UP TO HANDLE 6 COLUMNS/PAGE WITH A 6F20.14 FORMAT
C
C FOR THE COLUMNS.  IF A DIFFERENT NUMBER OF COLUMNS IS REQUIRED, CHANGE
C
C FORMATS 1000 AND 2000, AND INITIALIZE KCOL WITH THE NEW NUMBER OF
C
C COLUMNS.
C
C AUTHOR:  NELSON H.F. BEEBE, QUANTUM THEORY PROJECT, UNIVERSITY OF
C          FLORIDA, GAINESVILLE
C
C.......................................................................
      REAL*8 MATRIX
      INTEGER BEGIN
      DIMENSION MATRIX(1)
      CHARACTER*1 COLUMN(6),ASA(3),BLANK,CTL
      DATA COLUMN/'C','O','L','U','M','N'/,ASA/' ','0','-'/,BLANK/' '/
      DATA KCOL/6/,ZERO/0.D+00/
      CTL = BLANK
      IF ((NCTL.LE.3).AND.(NCTL.GT.0)) CTL = ASA(NCTL)
C
C LAST IS THE LAST COLUMN NUMBER IN THE ROW CURRENTLY BEING PRINTED
C
      LAST = MIN0(NROW,KCOL)
C
C BEGIN IS THE FIRST COLUMN NUMBER IN THE ROW CURRENTLY BEING PRINT%D.
C     A
      BEGIN=NROW-1
    5 BEGIN=BEGIN+1
      NCOL = 1
      WRITE (6,1000) (COLUMN,I,I = BEGIN,LAST)
      DO 40 K = BEGIN,NROW
      KTOTAL = (K*(K-1))/2 + BEGIN - 1
      DO 10 I = 1,NCOL
      IF (MATRIX(KTOTAL+I) .NE. ZERO) GO TO 20
   10 CONTINUE
      GO TO 30
   20 WRITE (6,2000) CTL,K,(MATRIX(KTOTAL+I), I = 1,NCOL)
   30 IF (K .LT. (BEGIN+KCOL-1)) NCOL = NCOL + 1
   40 CONTINUE
   50 LAST = MIN0(LAST+KCOL,NROW)
      IF (BEGIN.LT.NCOL) GO TO 5
 1000 FORMAT ('-',12X,6(5X,6A1,I4,5X))
 2000 FORMAT (A1,4H ROW,I4,2X,6F20.14)
      RETURN
      END
