      SUBROUTINE PUTDC(D,L3MX,LMAX,IW)
      IMPLICIT REAL*8(A-H,O-Z)
C-----------------------------------------------------------------------
C
C     PUTDC...
C
C        THIS ROUTINE PRINTS THE D-COEFFICIENTS GENERATED BY GENDC AND
C     RECOMBINED BY DCOEF FOR THE ROTATION OF REAL SPHERICAL HARMONICS.
C
C        D(*)... D-COEFFICIENTS.
C        LMAX... MAXIMUM L-VALUE.
C        L3MX... DIMENSION OF D(*).
C        IW..... FORTRAN I/O UNIT TO BE PRINTED ON.
C
C     ROUTINES CALLED:  DCOEF
C
C-----------------------------------------------------------------------
      DIMENSION D(L3MX,2)
	  WRITE (IW,1000)
      LMXP1=LMAX+1
      DO 30 IL=1,LMXP1
      L=IL-1
      LLP1=2*L+1
      DO 20 IML=1,LLP1
      ML=IML-L-1
      DO 10 ISIG=1,LLP1
      ISIGMA=ISIG-L-1
      DC=DCOEF(D,L,ML,ISIGMA)
      WRITE (IW,2000) L,ML,ISIGMA,DC
   10 CONTINUE
   20 CONTINUE
   30 CONTINUE
      RETURN
 1000 FORMAT('- L  ML  SIGMA         D-COEFFICIENT'/
     X       '+ _  __  _____         _____________'/' ')
 2000 FORMAT(' ',I3,I4,I5,F20.8)
      END
