      SUBROUTINE OCCMET(ONTRAN,OCC,STOVL,NORB,N2ORB)
      IMPLICIT REAL*8(A-H,O-Z)
C-----------------------------------------------------------------------
C
C     OCCMET...
C
C        THIS ROUTINE GENERATES THE METRIC INVERSE IN SYMMETRIC PACKED
C     FORM.  THE ROWS AND COLUMNS ARE EACH WEIGHTED BY THE CORRESPONDING
C     ORBITAL OCCUPATION NUMBERS.
C
C     VARIABLE DEFINITIONS:
C
C        ONTRAN(*,*)... METRIC INVERSE IN SQUARE FORM.
C        OCC(*)........ ORBITAL OCCUPATION NUMBERS.
C        STOVL(*)...... WEIGHTED METRIC INVERSE IN PACKED FORM.
C        NORB.......... NUMBER OF ORBITALS.
C        N2ORB......... =NORB*(NORB+1)/2.
C
C     ROUTINES CALLED:  SYMPAK;  DSQRT
C
C-----------------------------------------------------------------------
      DIMENSION ONTRAN(NORB,NORB),OCC(NORB),STOVL(N2ORB)
      DO 20 JORB=1,NORB
      DO 10 IORB=1,NORB
      ONTRAN(IORB,JORB)=DSQRT(OCC(IORB)*OCC(JORB))*ONTRAN(IORB,JORB)
   10 CONTINUE
   20 CONTINUE
      CALL SYMPAK(ONTRAN,STOVL,NORB,N2ORB)
      RETURN
      END
