      SUBROUTINE RBETA(COORD,NATOM,IATOM,JATOM,RAB,ALPH,BETA)
      IMPLICIT REAL*8(A-H,O-Z)
C-----------------------------------------------------------------------
C
C     RBETA...
C
C        THIS ROUTINE COMPUTES THE INTERNUCLEAR DISTANCE AND AZIMUTHAL
C     AND LONGITUDINAL ANGLES BETWEEN TWO ATOMS FROM THEIR CARTESIAN
C     COORDINATES.
C
C     DEFINITIONS:
C
C        COORD(1,IATOM)... X-COORDINATE OF THE I-TH ATOM.
C        COORD(2,JATOM)... Y-COORDINATE OF THE J-TH ATOM.
C                  ETC.,
C        RAB.............. INTERATOMIC DISTANCE.
C        ALPH............. LONGITUDINAL ANGLE (ABOUT Z-AXIS).
C        BETA............. AZIMUTHAL ANGLE (TILT FROM Z-AXIS).
C        NATOM............ TOTAL NUMBER OF ATOMS, DIMENSION OF COORD(*).
C
C     ENTRY:  RBETA2...
C
C        THIS ENTRY INPUTS THE CARTESIAN DISPLACEMENTS DIRECTLY
C     (X12,Y12,Z12).
C
C     ROUTINES CALLED:  DSQRT, DATAN2
C
C-----------------------------------------------------------------------
      DIMENSION COORD(3,NATOM)
	  
      X1=COORD(1,IATOM)
      X2=COORD(1,JATOM)
      X12=X2-X1
      Y1=COORD(2,IATOM)
      Y2=COORD(2,JATOM)
      Y12=Y2-Y1
      Z1=COORD(3,IATOM)
      Z2=COORD(3,JATOM)
      Z12=Z2-Z1
	  CALL RBETA2(X12,Y12,Z12,RAB,ALPH,BETA)
      RETURN
      END
C
C...
      SUBROUTINE RBETA2(X,Y,Z,RAB,ALPH,BETA)
      IMPLICIT REAL*8(A-H,O-Z)
      DATA ZERO/0.0D0/

      R=DSQRT(X*X+Y*Y)
      RAB=DSQRT(R*R+Z*Z)
      ALPH=ZERO
      BETA=ZERO
      IF (RAB.EQ.ZERO) RETURN
      BETA=DATAN2(R,Z)
      IF (R.EQ.ZERO) RETURN
      ALPH=DATAN2(Y,X)
      RETURN
      END
